export const factionsData = [
  {
    name: "Iron Legion",
    description: "A disciplined military order renowned for their iron will. Their leadership is trying to bring law and structure to every corner of the continent.",
    mobTypes: ["soldier", "knight", "standard bearer", "legionnaire", "war engineer"],
    influence: 7,
    color: "#575757",
    icon: "🛡️",
  },
  {
    name: "Verdant Pact",
    description: "Protectors of ancient forests and wild creatures. They aim to restore wild lands and limit the spread of civilization.",
    mobTypes: ["druid", "beast", "treewarden", "vinecaller", "forest sentinel"],
    influence: 5,
    color: "#228B22",
    icon: "🌿",
  },
  {
    name: "Shadow Veil",
    description: "Secretive agents and spies operating in the dark. Their agents work behind the scenes to balance power among rulers.",
    mobTypes: ["rogue", "assassin", "infiltrator", "shade", "spy handler"],
    influence: 6,
    color: "#2C2C2C",
    icon: "🕵️‍♂️",
  },
  {
    name: "Azure Order",
    description: "Mages who draw power from the sea and sky. Their leadership is working to prevent magical catastrophes and maintain equilibrium.",
    mobTypes: ["mage", "sorcerer", "stormcaller", "tideweaver", "skywatcher"],
    influence: 6,
    color: "#1E90FF",
    icon: "💧",
  },
  {
    name: "Crimson Banner",
    description: "Warriors driven by honor and bloodshed. They are determined to win every major tournament and prove their supremacy in combat.",
    mobTypes: ["barbarian", "warrior", "duelist", "battle chanter", "blood knight"],
    influence: 8,
    color: "#B22222",
    icon: "🩸",
  },
  {
    name: "Golden Dawn",
    description: "Clerics and paladins who worship the rising sun. Their priests travel far and wide, hoping to bring hope to the hopeless.",
    mobTypes: ["cleric", "paladin", "lightbearer", "sun acolyte", "radiant herald"],
    influence: 7,
    color: "#FFD700",
    icon: "🌞",
  },
  {
    name: "Silent Crescent",
    description: "Assassins who strike under the cover of night. Their leadership is quietly removing influential criminals from the city.",
    mobTypes: ["assassin", "thief", "nightblade", "moonshadow", "silencer"],
    influence: 5,
    color: "#C0C0C0",
    icon: "🌙",
  },
  {
    name: "Frostbind",
    description: "Ice-wielding warriors from the frozen north. They aim to defend their homeland’s borders and preserve their ancient traditions.",
    mobTypes: ["berserker", "shaman", "frost giant", "ice witch", "glacier sentinel"],
    influence: 4,
    color: "#00BFFF",
    icon: "❄️",
  },
  {
    name: "Emerald Circle",
    description: "Druids and healers who revere the earth. Their focus is on curing the blight threatening the sacred groves.",
    mobTypes: ["druid", "healer", "briar guardian", "grovekeeper", "blight warder"],
    influence: 5,
    color: "#50C878",
    icon: "🍀",
  },
  {
    name: "Bronze Fang",
    description: "Mercenaries with a reputation for loyalty to gold. They are always on the lookout for the most profitable contracts.",
    mobTypes: ["warrior", "mercenary", "pit fighter", "blade for hire", "coin hound"],
    influence: 4,
    color: "#CD7F32",
    icon: "🐺",
  },
  {
    name: "Stormguard",
    description: "Defenders wielding the power of storms. After returning home to find their town destroyed, their focus changed to keeping pirates and monsters away from coastal cities.",
    mobTypes: ["paladin", "elementalist", "tempest knight", "storm herald", "wave breaker"],
    influence: 7,
    color: "#4682B4",
    icon: "⚡",
  },
  {
    name: "Obsidian Brotherhood",
    description: "Shadowy cultists with a penchant for dark magic. They are rumored to be preparing rituals to call forth ancient powers for a mysterious purpose.",
    mobTypes: ["warlock", "cultist", "shadow priest", "obsidian adept", "void speaker"],
    influence: 6,
    color: "#181818",
    icon: "🌀",
  },
  {
    name: "Celestial Choir",
    description: "Angelic beings who bring hope and healing. They aim to unite the scattered peoples under a banner of peace.",
    mobTypes: ["angel", "cleric", "seraphim", "harpist", "blessed singer"],
    influence: 9,
    color: "#E6E6FA",
    icon: "🎶",
  },
  {
    name: "Sunfire Accord",
    description: "Pyromancers and warriors of the blazing desert. Their leadership is striving to unearth lost cities beneath the sands.",
    mobTypes: ["pyromancer", "warrior", "sandstalker", "flame dancer", "ash walker"],
    influence: 5,
    color: "#FF8C00",
    icon: "🔥",
  },
  {
    name: "Twilight Enclave",
    description: "Scholars and monks who study the mysteries of dusk. They aim to interpret ancient prophecies and warn the world of what’s to come.",
    mobTypes: ["monk", "scholar", "oracle", "twilight scribe", "gloam mystic"],
    influence: 4,
    color: "#8A2BE2",
    icon: "🦉",
  },
  {
    name: "Silver Spire",
    description: "Noble houses and diplomats from a great city. Their leadership is trying to forge new alliances and secure their legacy.",
    mobTypes: ["noble", "diplomat", "silver guard", "courtier", "banner knight"],
    influence: 8,
    color: "#C0C0C0",
    icon: "🏰",
  },
  {
    name: "Gilded Raiders",
    description: "Treasure hunters always chasing the next fortune. Their eyes are set on the legendary lost vault of the Golden King.",
    mobTypes: ["raider", "thief", "trapmaster", "vault breaker", "gold seeker"],
    influence: 3,
    color: "#FFD700",
    icon: "💰",
  },
  {
    name: "Bloodroot Clan",
    description: "Savage forest warriors with a thirst for battle. They aim to reclaim their ancestral groves from outsiders.",
    mobTypes: ["barbarian", "shaman", "blood druid", "root caller", "wild reaver"],
    influence: 6,
    color: "#8B0000",
    icon: "🌳",
  },
  {
    name: "Starborn",
    description: "Mystics who claim heritage from the stars. Their sages are determined to build an observatory to unlock cosmic secrets.",
    mobTypes: ["mystic", "sorcerer", "star oracle", "cosmic seer", "voidwalker"],
    influence: 6,
    color: "#87CEEB",
    icon: "✨",
  },
  {
    name: "Ivory Sentinels",
    description: "Elite guardians sworn to protect the innocent. Their leadership is expanding the order to defend a holy city claimed by their god.",
    mobTypes: ["paladin", "guardian", "banneret", "shieldbearer", "divine warden"],
    influence: 7,
    color: "#FFFFF0",
    icon: "🦄",
  },
  {
    name: "Grim Company",
    description: "Veteran soldiers haunted by their past. They take on the missions others won’t, searching for redemption.",
    mobTypes: ["veteran", "mercenary", "gravewalker", "iron resolve", "pale rider"],
    influence: 5,
    color: "#696969",
    icon: "☠️",
  },
  {
    name: "Amber Watch",
    description: "Rangers who protect the borderlands. Their scouts are ensuring safe passage for caravans through dangerous territory.",
    mobTypes: ["ranger", "scout", "beast tracker", "amber archer", "trail warden"],
    influence: 4,
    color: "#FFBF00",
    icon: "🦊",
  },
  {
    name: "Cobalt Assembly",
    description: "Alchemists and artificers of great repute. They specialize with inventions to revolutionize travel and communication.",
    mobTypes: ["alchemist", "artificer", "gearwright", "steamwright", "arcane machinist"],
    influence: 6,
    color: "#0047AB",
    icon: "⚗️",
  },
  {
    name: "Wildheart Coalition",
    description: "Nomadic clans united in harmony with beasts. Their leadership is trying to defend ancient habitats and migratory routes.",
    mobTypes: ["hunter", "beastmaster", "wildspeaker", "herd guardian", "skyrider"],
    influence: 4,
    color: "#A0522D",
    icon: "🐾",
  },
  {
    name: "Venom Syndicate",
    description: "Poisoners and smugglers ruling the underworld. They aim to control illicit trade in every major city.",
    mobTypes: ["assassin", "smuggler", "toxin brewer", "venomblade", "shade courier"],
    influence: 6,
    color: "#228B22",
    icon: "🐍",
  },
  {
    name: "Lunar Dominion",
    description: "Worshippers of the moon and masters of illusions. Their leadership is trying to usher in a new age of shadow and mystery.",
    mobTypes: ["illusionist", "priest", "moonblade", "lunarch", "shadow dancer"],
    influence: 5,
    color: "#B0E0E6",
    icon: "🌒",
  },
  {
    name: "Thunderhoof Cavalry",
    description: "Elite cavalry renowned for their thunderous charges. Their riders are training for unmatched battlefield dominance.",
    mobTypes: ["cavalry", "warrior", "storm lancer", "hoof captain", "sky charger"],
    influence: 5,
    color: "#8B4513",
    icon: "🐎",
  },
  {
    name: "Onyx Covenant",
    description: "Necromancers and death cultists. This group seeks to unlock the forbidden secrets of immortality.",
    mobTypes: ["necromancer", "cultist", "bone mage", "plague herald", "tomb caller"],
    influence: 7,
    color: "#353839",
    icon: "💀",
  },
  {
    name: "Scarlet Hand",
    description: "Thieves' guild infamous for their daring heists. Their leadership is planning to steal the crown jewels from the royal treasury.",
    mobTypes: ["thief", "rogue", "pickpocket", "red hood", "lockbreaker"],
    influence: 6,
    color: "#B22222",
    icon: "🖐️",
  },
  {
    name: "Sunken Court",
    description: "Aquatic aristocrats governing the deep seas. They are seeking to broker a beneficial treaty between surface and underwater nations.",
    mobTypes: ["merfolk", "sea witch", "coral knight", "depth caller", "tide baron"],
    influence: 5,
    color: "#00CED1",
    icon: "🌊",
  },
  {
    name: "Ivory Talon",
    description: "Aerial warriors and strategists. Their leadership works to organize and secure control of the skies above the kingdom.",
    mobTypes: ["griffin","griffin rider", "archer", "sky captain", "wind sprite"],
    influence: 6,
    color: "#FFF8DC",
    icon: "🦅",
  },
  {
    name: "Obsidian Wardens",
    description: "Guardians of ancient secrets and ruins. Their members are preventing forbidden artifacts from falling into the wrong hands.",
    mobTypes: ["warden", "golem", "crypt sentinel", "tomb guardian", "arcane sentinel"],
    influence: 5,
    color: "#3B3B3B",
    icon: "🗿",
  },
  {
    name: "Sunspire Monks",
    description: "Enlightened monks from the mountain peaks. Their leadership is spreading wisdom by founding new monasteries far and wide.",
    mobTypes: ["monk", "sage", "wayfarer", "sun ascetic", "mountain hermit"],
    influence: 4,
    color: "#FFD700",
    icon: "🛕",
  },
  {
    name: "Feral Kin",
    description: "Werecreatures struggling for acceptance. They hope to find a cure for the ancient curse that afflicts them, and to stop its further spread.",
    mobTypes: ["werewolf", "wereboar", "skinwalker", "moon cursed", "wildling"],
    influence: 4,
    color: "#8B8680",
    icon: "🐺",
  },
  {
    name: "Radiant Covenant",
    description: "Healers and priests of the light. Their leadership is working to establish sanctuaries in every major city.",
    mobTypes: ["priest", "healer", "luminary", "sunward", "blessed hand"],
    influence: 7,
    color: "#FFFAF0",
    icon: "💡",
  },
  {
    name: "Twilight Marauders",
    description: "Mercenary raiders adept at striking with surprise. Their scouts strike enemy camps before dawn, disrupting supply lines.",
    mobTypes: ["raider", "scout", "duskblade", "night prowler", "camp burner"],
    influence: 5,
    color: "#483D8B",
    icon: "🦇",
  },
  {
    name: "Mossback Assembly",
    description: "Tortle sages and lorekeepers. Their elders are compiling a great scroll to record the world’s history.",
    mobTypes: ["tortle", "sage", "herbalist", "shell scribe", "rootwalker"],
    influence: 3,
    color: "#556B2F",
    icon: "🐢",
  },
  {
    name: "Gloomblade Syndicate",
    description: "Blademasters who thrive in darkness. They aim to train the ultimate swordmaster in the art of shadow combat in preparation for a foretold trial known only to them.",
    mobTypes: ["blademaster", "assassin", "shadow dancer", "gloom warden", "vengeance seeker"],
    influence: 6,
    color: "#343434",
    icon: "⚔️",
  },
  {
    name: "Jade Lotus",
    description: "Mystic order of monks and sorcerers. Their leadership works to preserve ancient martial arts and arcane wisdom.",
    mobTypes: ["monk", "sorcerer", "lotus adept", "jade fist", "arcane gardener"],
    influence: 5,
    color: "#00FF7F",
    icon: "🥋",
  },
  {
    name: "Ironroot Enclave",
    description: "Defenders of the world tree and its secrets. They strive to stop uncaring mercantile companies from destroying sacred forests.",
    mobTypes: ["guardian", "druid", "thorn sentinel", "root warden", "barkskin"],
    influence: 8,
    color: "#556B2F",
    icon: "🌲",
  },
  {
    name: "Nightshade Cartel",
    description: "Dealers of forbidden alchemy and rare toxins. Their network is securing exclusive access to rare herbs and recipes.",
    mobTypes: ["alchemist", "rogue", "venomblade", "shade peddler", "poison crafter"],
    influence: 6,
    color: "#483D8B",
    icon: "🧪",
  },
  {
    name: "Runestone Council",
    description: "Wizards and keepers of ancient runes. Their scholars are working to decipher the last unbroken rune stone.",
    mobTypes: ["wizard", "scribe", "runecaster", "glyph keeper", "arcane archivist"],
    influence: 7,
    color: "#4169E1",
    icon: "📜",
  },
  {
    name: "Emberkin",
    description: "Fire elementals and their mortal allies. Their leadership is seeking to ignite the dormant volcano and reshape the land.",
    mobTypes: ["elemental", "pyromancer", "ash priest", "ember guard", "flame warden"],
    influence: 4,
    color: "#FF4500",
    icon: "🔥",
  },
  {
    name: "Frostwolf Clan",
    description: "A brotherhood of shamans and spectral wolves who roam the tundra, uniting northern tribes beneath one banner, against the encroaching thaw.",
    mobTypes: ["shaman", "wolf", "spirit tracker", "ice howler", "winter scout"],
    influence: 6,
    color: "#B0C4DE",
    icon: "🐺",
  },
  {
    name: "Dawnbringers",
    description: "Crusaders who fight for justice. Their leadership is rooting out corruption from the royal court.",
    mobTypes: ["crusader", "paladin", "justicar", "sunblade", "vigilant"],
    influence: 8,
    color: "#FFFACD",
    icon: "⚔️",
  },
  {
    name: "Duskwalkers",
    description: "Guides of the dead and spirit mediums. Their monks are shepherding souls to the afterlife with solemn rituals.",
    mobTypes: ["medium", "spirit", "wraithspeaker", "nightwatcher", "veil walker"],
    influence: 5,
    color: "#696969",
    icon: "👻",
  },
  {
    name: "Crystal Syndicate",
    description: "Merchants and smugglers of rare gems. Their traders are looking to monopolize the lucrative crystal market.",
    mobTypes: ["merchant", "smuggler", "jewel appraiser", "crystal mage", "facet thief"],
    influence: 4,
    color: "#B0E0E6",
    icon: "💎",
  },
  {
    name: "Sandstrider Merchants' Guild",
    description: "Desert traders famed for their caravans. Their leadership is expanding trade routes for rare spices and silks.",
    mobTypes: ["merchant", "camel handler", "caravan master", "sand guide", "spice trader"],
    influence: 3,
    color: "#DEB887",
    icon: "🐪",
  },
  {
    name: "Stormsong Minstrels",
    description: "Weather-weaving bards who perform amidst thunder and rain, the Stormsong Minstrels compose melodies said to summon storms and calm tempests. Their goal: to craft a symphony that can change the fate of the world.",
    mobTypes: ["bard", "sorcerer", "tempest singer", "wind harpist", "raincaller"],
    influence: 4,
    color: "#00CED1",
    icon: "🎵",
  },
  {
    name: "Violet Oath",
    description: "Vigilantes who fight from the shadows. Their leadership is quietly bringing justice to those above the law.",
    mobTypes: ["vigilante", "rogue", "maskbearer", "shadow avenger", "cloak agent"],
    influence: 5,
    color: "#9400D3",
    icon: "🦸‍♂️",
  },
  {
    name: "Copper Foxes",
    description: "Cunning scouts and expert trackers. Their scouts are charting every corner of the known world, and cataloguing its flora and fauna.",
    mobTypes: ["scout", "tracker", "foxkin", "pathfinder", "burrower"],
    influence: 4,
    color: "#B87333",
    icon: "🦊",
  },
];